### ISSUE TITLE
yammer auth error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manieyedone85/socialauth-android#149]
```
What steps will reproduce the problem?
1.Set up yammer auth
2.Call authorize

I have tested twitter and facebook, and they work without any problems.

This is what I get from trying yammer:
some kind of problem with resources

E/AndroidRuntime(32215): android.content.res.Resources$NotFoundException: 
Resource ID #0x0
E/AndroidRuntime(32215):    at 
android.content.res.Resources.getValue(Resources.java:897)
E/AndroidRuntime(32215):    at 
android.content.res.Resources.getDrawable(Resources.java:585)
E/AndroidRuntime(32215):    at 
org.brickred.socialauth.android.SocialAuthDialog.setUpTitle(SocialAuthDialog.jav
a:191)
E/AndroidRuntime(32215):    at 
org.brickred.socialauth.android.SocialAuthDialog.onCreate(SocialAuthDialog.java:
146)
E/AndroidRuntime(32215):    at 
android.app.Dialog.dispatchOnCreate(Dialog.java:307)
E/AndroidRuntime(32215):    at android.app.Dialog.show(Dialog.java:225)
E/AndroidRuntime(32215):    at 
org.brickred.socialauth.android.SocialAuthAdapter$4$1.run(SocialAuthAdapter.java
:644)
E/AndroidRuntime(32215):    at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime(32215):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(32215):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime(32215):    at 
android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime(32215):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(32215):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(32215):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime(32215):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime(32215):    at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `vdarzni...@gmail.com` on 21 Feb 2014 at 3:57

**Comment by GoogleCodeExporter** [comment]
```
I didn't have required resources. Can remove this
```

Original comment by `vdarzni...@gmail.com` on 26 Feb 2014 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
Hi,

You need to add Yammer icon in resources. It is prerequirement. check examples.
```

Original comment by `vineet.a...@3pillarglobal.com` on 3 Mar 2014 at 7:13
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Hi,
 I'm getting error for yahoo : 
03-13 16:55:56.140: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:55:56.160: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:56:20.930: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:56:20.990: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:57:23.580: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:57:23.600: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:57:31.050: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:57:31.110: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:58:40.200: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:58:40.210: E/Environment(11674): getExternalStorageState/mnt/sdcard
03-13 16:58:40.470: E/WindowManager(11674): Activity 
com.aeldata.techmax.activity.LoginActivity has leaked window 
com.android.internal.policy.impl.PhoneWindow$DecorView@40dc9550 that was 
originally added here
03-13 16:58:40.470: E/WindowManager(11674): android.view.WindowLeaked: Activity 
com.aeldata.techmax.activity.LoginActivity has leaked window 
com.android.internal.policy.impl.PhoneWindow$DecorView@40dc9550 that was 
originally added here
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.view.ViewRoot.<init>(ViewRoot.java:291)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:249)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:193)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:
118)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.view.Window$LocalWindowManager.addView(Window.java:532)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.app.Dialog.show(Dialog.java:269)
03-13 16:58:40.470: E/WindowManager(11674):     at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient.onPageS
tarted(SocialAuthDialog.java:375)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:267)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.os.Handler.dispatchMessage(Handler.java:99)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.os.Looper.loop(Looper.java:132)
03-13 16:58:40.470: E/WindowManager(11674):     at 
android.app.ActivityThread.main(ActivityThread.java:4126)
03-13 16:58:40.470: E/WindowManager(11674):     at 
java.lang.reflect.Method.invokeNative(Native Method)
03-13 16:58:40.470: E/WindowManager(11674):     at 
java.lang.reflect.Method.invoke(Method.java:491)
03-13 16:58:40.470: E/WindowManager(11674):     at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
03-13 16:58:40.470: E/WindowManager(11674):     at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
03-13 16:58:40.470: E/WindowManager(11674):     at 
dalvik.system.NativeStart.main(Native Method)
03-13 16:58:42.810: E/AndroidRuntime(11674): FATAL EXCEPTION: main
03-13 16:58:42.810: E/AndroidRuntime(11674): 
java.lang.IllegalArgumentException: View not attached to window manager
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:486)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:306)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.ja
va:129)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.app.Dialog.dismissDialog(Dialog.java:306)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.app.Dialog.access$000(Dialog.java:73)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.app.Dialog$1.run(Dialog.java:110)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.app.Dialog.dismiss(Dialog.java:296)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$3.onNew
Picture(SocialAuthDialog.java:439)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.webkit.WebView$PrivateHandler.handleMessage(WebView.java:11286)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.os.Handler.dispatchMessage(Handler.java:99)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.os.Looper.loop(Looper.java:132)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
android.app.ActivityThread.main(ActivityThread.java:4126)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
java.lang.reflect.Method.invokeNative(Native Method)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
java.lang.reflect.Method.invoke(Method.java:491)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
03-13 16:58:42.810: E/AndroidRuntime(11674):    at 
dalvik.system.NativeStart.main(Native Method)
```

Original comment by `rosh.sin...@gmail.com` on 13 Mar 2014 at 8:14

**Comment by GoogleCodeExporter** [comment]
```
problem comes when after successful authentication...
```

Original comment by `rosh.sin...@gmail.com` on 13 Mar 2014 at 8:16
