### ISSUE TITLE
Twitter Authentication Issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manieyedone85/socialauth-android#30]
```
Updated the libs files from the SVN
Filled the call back url

Still i cant get the login window... what might be the reason??

Logcat:
org.brickred.socialauth.exception.SocialAuthConfigurationException: Application 
keys are not correct. The server running the application should be same that 
was registered to get the keys.
at 
org.brickred.socialauth.util.OAuthConsumer.getRequestToken(OAuthConsumer.java:20
6)
at 
org.brickred.socialauth.oauthstrategy.OAuth1.getLoginRedirectURL(OAuth1.java:69)
at 
org.brickred.socialauth.provider.TwitterImpl.getLoginRedirectURL(TwitterImpl.jav
a:142)
at 
org.brickred.socialauth.SocialAuthManager.getAuthURL(SocialAuthManager.java:161)
at 
org.brickred.socialauth.SocialAuthManager.getAuthenticationUrl(SocialAuthManager
.java:115)
at 
org.brickred.socialauth.android.SocialAuthAdapter$3.run(SocialAuthAdapter.java:3
61)
at java.lang.Thread.run(Thread.java:1019)
org.brickred.socialauth.android.SocialAuthError: URL Authentication error
at 
org.brickred.socialauth.android.SocialAuthAdapter$3.run(SocialAuthAdapter.java:3
79)
at java.lang.Thread.run(Thread.java:1019)

Thanks in advance....

```

Original issue reported on code.google.com by `njarunnj` on 31 Jan 2013 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Please tell me in your twitter account :

1. What you have filled in callback url. If it is empty. Fill any dummy url in 
it.
2. Have you given Read and write access permission.


```

Original comment by `vineet.a...@3pillarglobal.com` on 31 Jan 2013 at 6:09

**Comment by GoogleCodeExporter** [comment]
```
yea i used http://schogini.in as call back url. Also has read, write
permissions....

On 1/31/13, socialauth-android@googlecode.com
<socialauth-android@googlecode.com> wrote:
```

Original comment by `njarunnj` on 31 Jan 2013 at 6:28

**Comment by GoogleCodeExporter** [comment]
```
you can check two more things which i have faced some time. Check your phone is 
taking network date and time in settings- date and time. secondly have good 
wifi connection . i have noticed in low speed sometimes twitter not opens.

also check in real device.
```

Original comment by `vineet.a...@3pillarglobal.com` on 31 Jan 2013 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
okay...will check again. Also abt your project in the svn, can u move
it to the downloads section?! It would be very helpful. Once again
thanks for the wonderful share....

On 2/1/13, socialauth-android@googlecode.com
<socialauth-android@googlecode.com> wrote:
```

Original comment by `njarunnj` on 31 Jan 2013 at 6:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `vineet.a...@3pillarglobal.com` on 7 Feb 2013 at 6:12
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
no....its not yet working!!
```

Original comment by `njarunnj` on 7 Feb 2013 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
Its not working yet.. with the latest 3.0 jar.. same error.. please fix this 
bug.. :(
```

Original comment by `srikarav...@gmail.com` on 18 Nov 2013 at 9:18

**Comment by GoogleCodeExporter** [comment]
```
hey guys,  i get almost the same error message:

D/SocialAuthAdapter(28827): Selected provider is twitter
D/SocialAuthAdapter(28827): Loading keys and secrets from configuration
I/SocialAuthConfig(28827): Loading application configuration
D/SocialAuthAdapter(28827): Starting webview for authentication
I/TwitterImpl(28827): Loading plugins
I/TwitterImpl(28827): Loading plugin :: 
org.brickred.socialauth.plugin.twitter.FeedPluginImpl
I/TwitterImpl(28827): Loading plugin :: 
org.brickred.socialauth.plugin.twitter.AlbumsPluginImpl
I/TwitterImpl(28827): Determining URL for redirection
I/OAuth1  (28827): Determining URL for redirection
D/audio_hw_primary(  177): select_devices: out_snd_device(2: speaker) 
in_snd_device(0: )
D/ACDB-LOADER(  177): ACDB -> send_afe_cal
D/SocialAuthError(28827): 
org.brickred.socialauth.exception.SocialAuthConfigurationException: Application 
keys are not correct. The server running the application should be same that 
was registered to get the keys.
W/System.err(28827): org.brickred.socialauth.android.SocialAuthError: URL 
Authentication error
W/System.err(28827):    at 
org.brickred.socialauth.android.SocialAuthAdapter$4.run(SocialAuthAdapter.java:6
53)
W/System.err(28827):    at java.lang.Thread.run(Thread.java:841)
D/Share-Bar(28827): URL Authentication error
I/CordovaLog(28827): Changing log level to DEBUG(3)
I/CordovaLog(28827): Found start page location: index.html
D/Whitelist(28827): Unlimited access to network resources
D/CordovaActivity(28827): Resuming the App
D/CordovaActivity(28827): CB-3064: The errorUrl is null


i use the share-bar example's configuration, but it is not working.
the helping is appreciated.
thanks
```

Original comment by `e.faridh...@gmail.com` on 22 Oct 2014 at 3:44
