### ISSUE TITLE
Warnings with final product, not during testing and development

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manieyedone85/socialauth-android#38]
```
I get the following warnings on my final product, and I'm hoping someone could 
explain it:

D/SocialAuthAdapter? (18237): Selected provider is facebook

D/SocialAuthAdapter? (18237): Starting webview for authentication

W/SocialAuthManager? (18237): org.brickred.socialauth.provider.FacebookImpl? 
does not implement a constructor 
org.brickred.socialauth.provider.FacebookImpl?(Poperties props)

W/System.err(18237): java.lang.InstantiationException?: 
org.brickred.socialauth.provider.FacebookImpl?

W/System.err(18237): at java.lang.Class.newInstanceImpl(Native Method)

W/System.err(18237): at java.lang.Class.newInstance(Class.java:1409)

W/System.err(18237): at org.brickred.socialauth.SocialAuthManager?.b(Unknown 
Source)

W/System.err(18237): at org.brickred.socialauth.SocialAuthManager?.a(Unknown 
Source)

W/System.err(18237): at org.brickred.socialauth.SocialAuthManager?.a(Unknown 
Source)

W/System.err(18237): at 
org.brickred.socialauth.android.SocialAuthAdapter?$3.run(Unknown Source)

W/System.err(18237): at java.lang.Thread.run(Thread.java:1019)

What is the expected output? What do you see instead?
During development everything works fine, and everything I submit is posted on 
facebook... But the final product logs those messages and does nothing. The 
same thing happens on the other provider I use (Twitter).

What version of the product are you using? On what operating system?

socialauth-4.0.jar 

socialauth-android.jar


Please provide any additional information below.

I do use proguard with the following:

-keep class org.brickred. -dontwarn org.brickred.


Please advise, and thank you for your time.

Best regards

```

Original issue reported on code.google.com by `eduardom...@gmail.com` on 28 Feb 2013 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
Please check aare you getting same logs for share-bar , customui and 
share-button examples
```

Original comment by `vineet.a...@3pillarglobal.com` on 28 Feb 2013 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
Well it all worked fine with the share-bar , customui and share-button 
examples. Then I checked my configuration and noticed that I had proguarg set, 
so I did the same with the examples... and then a serie of warnings came out of 
the compilation:

[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.AbstractProvider: can't find referenced class 
org.apache.commons.logging.LogFactory

[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.oauthstrategy.Hybrid: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.oauthstrategy.Hybrid: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.oauthstrategy.OAuth1: can't find referenced class 
org.apache.commons.logging.LogFactory
org.brickred.socialauth.provider.FacebookImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.FourSquareImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.FourSquareImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.GenericOAuth1Provider: can't find referenced 
class org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.GenericOAuth1Provider: can't find referenced 
class org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.GenericOAuth2Provider: can't find referenced 
class org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.GenericOAuth2Provider: can't find referenced 
class org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.GoogleImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.GoogleImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.HotmailImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.HotmailImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.LinkedInImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.LinkedInImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.MendeleyImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.MendeleyImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.MySpaceImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.MySpaceImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.OpenIDException
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.OpenIDException
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ParameterList
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ParameterList
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.VerificationResult
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.discovery.Identifier
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.VerificationResult
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthSuccess
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthSuccess
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthSuccess
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchResponse
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchResponse
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerException
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.OpenIDException
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ParameterList
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.VerificationResult
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.discovery.Identifier
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthSuccess
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchResponse
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.VerificationResult
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.discovery.Identifier
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.ConsumerManager
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.discovery.DiscoveryInformation
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.OpenIDException
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ax.FetchResponse
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.AuthSuccess
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.message.ParameterList
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.consumer.VerificationResult
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.discovery.Identifier
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.OpenIdImpl: can't find referenced class 
org.openid4java.OpenIDException
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.RunkeeperImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.RunkeeperImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.SalesForceImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.SalesForceImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.TwitterImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.TwitterImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.YahooImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.YahooImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.YammerImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.provider.YammerImpl: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.HttpUtil: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.HttpUtil: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.OAuthConsumer: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.OAuthConsumer: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.OpenIdConsumer: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.OpenIdConsumer: can't find referenced class 
org.apache.commons.logging.LogFactory
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.SocialAuthUtil: can't find referenced class 
javax.servlet.http.HttpServletRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.SocialAuthUtil: can't find referenced class 
javax.servlet.http.HttpServletRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.SocialAuthUtil: can't find referenced class 
javax.servlet.http.HttpServletRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.SocialAuthUtil: can't find referenced class 
javax.servlet.http.HttpServletRequest
[2013-02-28 12:25:37 - custom-ui] Warning: 
org.brickred.socialauth.util.SocialAuthUtil: can't find referenced class 
javax.servlet.http.HttpServletRequest
[2013-02-28 12:25:37 - custom-ui] Warning: there were 111 unresolved references 
to classes or interfaces.
[2013-02-28 12:25:37 - custom-ui]          You may need to specify additional 
library jars (using '-libraryjars').
[2013-02-28 12:25:37 - custom-ui] java.io.IOException: Please correct the above 
warnings first.
[2013-02-28 12:25:37 - custom-ui]   at 
proguard.Initializer.execute(Initializer.java:321)
[2013-02-28 12:25:37 - custom-ui]   at 
proguard.ProGuard.initialize(ProGuard.java:211)
[2013-02-28 12:25:37 - custom-ui]   at 
proguard.ProGuard.execute(ProGuard.java:86)
[2013-02-28 12:25:37 - custom-ui]   at proguard.ProGuard.main(ProGuard.java:492)

So the issue here is possibly missing references ???!!!

Thank you for your response, I apologise for any inconvenience

Best regards


```

Original comment by `eduardom...@gmail.com` on 28 Feb 2013 at 12:29

**Comment by GoogleCodeExporter** [comment]
```
No Issues,

It helps community and we appreciate it.
```

Original comment by `vineet.a...@3pillarglobal.com` on 28 Feb 2013 at 12:33
- Changed state: **Done**
