### ISSUE TITLE
Retrieve Access Token (Facebook Twitter), set Custom Keys

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manieyedone85/socialauth-android#69]
```
What steps will reproduce the problem?
1.Retrieve Access Token
2.Set Custom Keys
3.

What is the expected output? What do you see instead?
1.) I would like to see the Facebook Access Token, and the Twitter access 
Token, or have method for obtaining it (if it doesn't exist)
2.) I would like to be able to set the App Identifiers for the various 
providers in the oauth_consumer.properties programmatically OR from code 
modifiable resource, such as strings.xml, without using that file, for example 
adapter.setKey(..), is this possible?


What version of the product are you using? On what operating system?
Latest on 4.0.3


Please provide any additional information below.


```

Original issue reported on code.google.com by `squorais...@gmail.com` on 7 May 2013 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
You can set custom keys in oauth.consumers files.

We are going to remove oauth.consumers in next version and keys will be 
embedded within code.
```

Original comment by `vineet.a...@3pillarglobal.com` on 22 May 2013 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
Hi , 

we have added a facility to add custom keys via code in latest sdk 2.5. we will 
be releasing its example soon on wiki. meanwhile you can play with addconfig 
method.
```

Original comment by `l...@3pillarglobal.com` on 10 Jun 2013 at 3:28
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
In addition to setting the API Key, upon successful authentication can you get 
the Access Token for Facebook and Twitter?
```

Original comment by `squorais...@gmail.com` on 11 Jun 2013 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
yes , use adapter.getcurrentprovider().getaccesstoken method
```

Original comment by `vineet.a...@3pillarglobal.com` on 14 Jun 2013 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
I noticed as of yesterday I'm unable to login to Twitter.   I get the
following exception now thrown when I try to log on.

owerManagerService: setTimeoutLocked::SmartSleep : after49500
06-14 12:01:54.104   9239-16313/com.vmn.androidbasicauth
W/System.err: org.brickred.socialauth.exception.SocialAuthException: Failed
to retrieve the user profile from
http://api.twitter.com/1/users/show.json?screen_name=**********. Staus :410
06-14 12:01:54.104   9239-16313/com.vmn.androidbasicauth
W/System.err: at
org.brickred.socialauth.provider.TwitterImpl.getProfile(TwitterImpl.java:184)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at
org.brickred.socialauth.provider.TwitterImpl.doVerifyResponse(TwitterImpl.java:1
69)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at
org.brickred.socialauth.provider.TwitterImpl.verifyResponse(TwitterImpl.java:158
)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at
org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:183)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:249)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at java.lang.Thread.run(Thread.java:856)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
D/SocialAuthError: org.brickred.socialauth.exception.SocialAuthException:
Failed to retrieve the user profile from
http://api.twitter.com/1/users/show.json?screen_name=fahsrouq. Staus :410
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: org.brickred.socialauth.android.SocialAuthError: Unknown Error
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:265)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth
W/System.err: at java.lang.Thread.run(Thread.java:856)
06-14 12:01:54.114   9239-16313/com.vmn.androidbasicauth       D/Share-Bar:
Unknown Error
06-14 12:01:54.244      758-844/?
 D/PowerManagerService: mIsLockZone =  false   mTiltAngle : 60.147705 value
: 5
06-14 12:01:54.364    1568-1574/?
 E/MP-Decision: DOWN Ld:14 Ns:1.100000 Ts:190 rq:1.000000 seq:236.000000
```

Original comment by `squorais...@gmail.com` on 14 Jun 2013 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
This occured as of yesterday. Facebook log on seems to work ok, but all of
a sudden the twitter log on stopped working.  Is there a resolution?


On Fri, Jun 14, 2013 at 12:03 PM, notsomuchaforementioned <
squoraishee@gmail.com> wrote:
```

Original comment by `squorais...@gmail.com` on 14 Jun 2013 at 4:04

**Comment by GoogleCodeExporter** [comment]
```
downlaod jar again , we have just fixed this issue.
```

Original comment by `vineet.a...@3pillarglobal.com` on 14 Jun 2013 at 4:16
